### ISSUE TITLE
Complete CI

### ISSUE THREAD

**Issue by mateusfg7** [mateusfg7/formatch#20]
Unify workflows `bump-tag.yml` and `eas-build.yml` to a unique CI workflow that bump tag, make a build and generate a new release with build as asset.

build and release e.g.:
```yaml
name: CI

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  SyncTag:
    // workflow codes...

  build:
    runs-on: ubuntu-latest
    needs: SyncTag
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Build app
      run: expo build:android
    - name: Get version from package.json
      id: version
      run: echo "::set-output name=version::$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')"
    - name: Rename APK
      run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/formatch_v${{ steps.version.outputs.version }}.apk
    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        artifact:
          - android/app/build/outputs/apk/release/formatch_v${{ steps.version.outputs.version }}.apk
```
